main: net.tfminecraft.PointShop.PointShop
api-version: '1.21.10'
name: PointShop
version: ${project.version}
author: Drefvelin

depend: [TLibs]

commands:
  pointshop:
      useage: /<command>
      description: PointShop Command